Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
